package com.example.plantcare.ui.theme

import androidx.compose.ui.graphics.Color

val primary_100 = Color(0xFF6FAC4C)
val primary_50 = Color(0xFFB4E29A)
val primary_20 = Color(0xFFE9FFDC)
val secondary_100 = Color(0xFFF4C517)
val secondary_60 = Color(0xFFF9DB45)
val secondary_20 = Color(0xFFFDF3D1)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFDFBFF)
val md_theme_light_onBackground = Color(0xFF001B3D)
val md_theme_light_surface = Color(0xFFFDFBFF)
val md_theme_light_onSurface = Color(0xFF001B3D)
val md_theme_light_surfaceVariant = Color(0xFFE0E4D6)
val md_theme_light_onSurfaceVariant = Color(0xFF43483E)
val md_theme_light_outline = Color(0xFF74796D)

val dark_primary = Color(0xFF1F5100)
val onPrimary = Color(0xFFB2F48B)
val dark_secondary = Color(0xFFF0C10F)
val onSecondary = Color(0xFF3D2F00)
val md_theme_dark_secondaryContainer = Color(0xFF574500)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFE089)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001B3D)
val md_theme_dark_onBackground = Color(0xFFD6E3FF)
val md_theme_dark_surface = Color(0xFF001B3D)
val md_theme_dark_onSurface = Color(0xFFD6E3FF)
val md_theme_dark_surfaceVariant = Color(0xFF43483E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4C8BB)
val md_theme_dark_outline = Color(0xFF8D9286)
val md_theme_dark_inverseOnSurface = Color(0xFF001B3D)
val md_theme_dark_inverseSurface = Color(0xFFD6E3FF)
val md_theme_dark_inversePrimary = Color(0xFF326B11)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF97D872)
val md_theme_dark_outlineVariant = Color(0xFF43483E)
val md_theme_dark_scrim = Color(0xFF000000)